spring.application.name=Fundo

# ============================================
# CONFIGURACION SQL SERVER - AgroExportDB
# ============================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AgroExportDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=tu_password_aqui
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Puerto del servidor
server.port=8080
